### ISSUE TITLE
Interface freezes in remote only mode when something goes wrong 

### ISSUE THREAD

**Issue by majorVitos** [ryo-currency/ryo-wallet#1]
It is no possible to change options in remote only mode when remote node is not responding. Interface freezed on attempt to connect. Only way to change config.json manually. Problem detected in windows

**Comment by mosu-forge** [comment]
@majorVitos Thanks for the issue. Just curious did you change the remote node to something other than `geo.ryoblocks.com`? 

What I can do in the next release is detect a timeout or inability to communicate with the remote node and redirect back to the config screen.

Also note if you just delete `config.json` you'll be dumped back to the initial setting screen. Of course editing `config.json` works too.

**Comment by majorVitos** [comment]
I changed remote node to 10.0.0.30, ip of my ubuntu server, just experiments and now it works fine.

**Comment by mosu-forge** [comment]
Got it, I will leave this issue open until it is resolved with extra start-up checks in the wallet.

**Comment by mosu-forge** [comment]
This is fixed in v1.1.0 which will be released in a few days.
