### ISSUE TITLE
Latest Version

### ISSUE THREAD

**Issue by blackparallax** [ryo-currency/ryo-wallet#12]
Is the pull request from 3 days ago an update we are required to install. I am using the Windows GUI. I am using v1.0.2-0.3.1.2, what is the pull request for? Sorry for the confusion. How do I update?

**Comment by mosu-forge** [comment]
@blackparallax The Pull Request is for v1.1.0-0.3.2.0. It will be merged today into master and tagged as a release. At that point I'll create and upload the binaries to the releases page.

It is not a required update, but it is recommended as it brings tons of new features. Check back at the end of the day and releases should be up.

**Comment by blackparallax** [comment]
Ah brilliant thanks 😎

**Comment by mosu-forge** [comment]
@blackparallax I assume you saw the release earlier today
