### ISSUE TITLE
"A JavaScript error occurred in the main process"

### ISSUE THREAD

**Issue by avalyn2** [ryo-currency/ryo-wallet#13]
The popups below appear when I start the wallet (currently using the Ryo Atom Wallet 1.0.0) and my wallet never starts. 

![screenshot from 2018-11-11 18-23-58](https://user-images.githubusercontent.com/32930476/48316092-0211f880-e5df-11e8-878b-a28fb9ee1f5e.png)

![screenshot from 2018-11-11 18-25-03](https://user-images.githubusercontent.com/32930476/48316102-2241b780-e5df-11e8-8533-76fbca213517.png)

The app is frozen on "Starting Wallet..."

![screenshot from 2018-11-11 18-27-19](https://user-images.githubusercontent.com/32930476/48316120-819fc780-e5df-11e8-87a9-bc4f2109c543.png)

Thanks!

**Comment by mosu-forge** [comment]
@avalyn2 my guess is that your directory `/home/chanchitos/.ryo` is not owned by the user `chanchitos`. This would probably have happened if you ran the ryo daemon with `su` in the past. Can you try running: `ls -la /home/chanchitos/.ryo` ? My guess is that it will show it owned by root user.

In any case you should be able to fix this by running: 
```
sudo chown -R chanchitos:chanchitos /home/chanchitos/.ryo
```

Let me know if that does not fix it, I will keep this issue open until I add on startup a check for correct directory permissions, and if denied show a more user friendly error message.

Also if that resolves the issue, please update your wallet to Atom 1.1.0 as it has some new features and bug fixes.

**Comment by avalyn2** [comment]
> ```
> sudo chown -R chanchitos:chanchitos /home/chanchitos/.ryo
> ```
hi, this solved the problem, thanks!

**Comment by mystery999** [comment]
I have a similar problem on win 10.
![default](https://user-images.githubusercontent.com/47169805/51961588-45596600-246e-11e9-9ba0-00d6d3749ab2.jpg)

**Comment by mystery999** [comment]
> I have a similar problem on win 10.
> ![default](https://user-images.githubusercontent.com/47169805/51961588-45596600-246e-11e9-9ba0-00d6d3749ab2.jpg)

you need to delete folders along the way:

C:\Program Files\Ryo\RyoWallet or /Applications/Ryo Wallet Atom.app
C:\ProgramData\ryo\wallets or /home/your_user_name/.ryo/wallets
C:\ProgramData\ryo\gui or /home/your_user_name/.ryo/gui

Do not forget to save the folder "wallets" with coins
