### ISSUE TITLE
Missing windows start menu icons

### ISSUE THREAD

**Issue by Nostradamus411** [ryo-currency/ryo-wallet#16]
Installed Atom wallet with ryo-wallet-win-installer-x64-1.1.0-0.3.2.0.exe and do not have icons in start menu.  Also if Atom is started from the start menu then the taskbar icon is also missing (maybe same root issue) but when launching Atom from the desktop shortcut the taskbar icon displays as expected.

![image](https://user-images.githubusercontent.com/38844339/48723336-f7152480-ebeb-11e8-98fd-e6701a52c3b9.png)

**Comment by mosu-forge** [comment]
Fixed in 1.2.0
