### ISSUE TITLE
Wallet takes hostages

### ISSUE THREAD

**Issue by pekster85** [ryo-currency/ryo-wallet#18]
Can someone EXPLAIN the following, cuz those brilliant minds seem to THINK they DID with the following;
"I had 100 coins, but when I spent 1 coin, wallet shows - that rest balance is locked?

The matter is how much inputs with what amount you had e.g:

    If you had 1 input in your wallet with 100 coins, you will have 99 (subtracting tx fee) coins locked and returned as change, that will need to wait 10 confirmations to be unlocked.
    If you had 10 inputs in wallet 10 coins each (same balance - 100 coins in total), after spending 1 coin, you will have 9 coins locked (subtracting tx fee) for 10 confirms and 90 coins of unlocked balance"

1) it explains NOTHING
2) its an example of WHAT?
3) wich brilliant donkey figured it smart to take users funds hostage????

**Comment by mosu-forge** [comment]
@pekster85 I apologize for the late reply due to the holidays. 

This is the nature of utxo based cryptocurrencies. This is behavior happens in all cryptonote based coins. Change must wait for 10 blocks to be confirmed before becoming spendable again.

**Comment by LeadManPL** [comment]
10 blocks? That is a lot! Is there any reason for this "design" ?

**Comment by mosu-forge** [comment]
@LeadManPL Just about every cryptonote coin uses 10 blocks for funds to be confirmed.
