### ISSUE TITLE
wallet balance and history not retrieved from blockchain upon recovery from seed

### ISSUE THREAD

**Issue by LeadManPL** [ryo-currency/ryo-wallet#24]
Wallet balance=0 and history is null/invisible, after wallet was retrieved from seed words.
Any hints?

**Comment by mosu-forge** [comment]
@LeadManPL have you confirmed that your restored RYoL address is correct? I would try restoring via CLI if possible to rule out if this is an issue on the GUI or your seed words.

**Comment by LeadManPL** [comment]
I still keep in mind to check it. Sorry for the delay.

**Comment by LeadManPL** [comment]
I have checked #24 with Ryo Wallet 1.3.1-0.4.0.1 and was able to recover wallet from seed.
I can only assume it may have been my fault: there is field called "Restroe from date" and maybe i have selected some date **after** my wallet was created.
