### ISSUE TITLE
Blockchain corruption following power failure

### ISSUE THREAD

**Issue by mattmill30** [ryo-currency/ryo-wallet#25]
The Atom Wallet (Ryo 'Lorentz Transform' (0.4.0.0-2933f3e/master)) is unable to load the blockchain after a powerloss scenario during an initial synchronisation.

RYOd was synchronising on a laptop which has 4.0GB RAM and was realistically utilising the PageFile. The laptop discharged and probably began to hibernate, but failed to fully hibernate before fully discharging.

Attempting to launch the Atom Wallet upon restart results in a hung "starting daemon" splash screen, and the log relevant portion of the log is snipped below. Full log attached.

I want to diagnose and attempt to repair the blockchain, rather than just resynchronise, because I don't want to rely on a wallet where a future powerloss scenario could result in another lengthy resychronisation.

2019-04-09 16:11:43.787	8688	INFO 	global	src/daemon/core.h:101	Initializing core...
2019-04-09 16:11:43.788	8688	INFO 	global	src/cryptonote_core/cryptonote_core.cpp:376	Loading blockchain from folder C:\ProgramData\ryo\lmdb02 ...
2019-04-09 16:11:43.852	8688	WARN 	default	src/blockchain_db/lmdb/db_lmdb.cpp:90	Error attempting to retrieve a hard fork version at height 0 from the db: MDB_NOTFOUND: No matching key/data pair found
2019-04-09 16:11:43.878	8688	WARN 	default	src/blockchain_db/lmdb/db_lmdb.cpp:90	Attempt to get block from height 0 failed -- block not in db
2019-04-09 16:11:43.879	8688	FATAL	net.http	src/daemon/daemon.cpp:207	Uncaught exception! Attempt to get block from height 0 failed -- block not in db

[ryod.log](https://github.com/ryo-currency/ryo-wallet/files/3063394/ryod.log)

**Comment by mattmill30** [comment]
This error is also referenced on the main monero project - https://github.com/monero-project/monero/issues/1598

**Comment by mattmill30** [comment]
Attempted ryod.exe --db-salvage. Log attached.

[ryod_db-salvage_10-04-2019.txt](https://github.com/ryo-currency/ryo-wallet/files/3064433/ryod_db-salvage_10-04-2019.txt)

**Comment by mosu-forge** [comment]
@mattmill30 First question just to confirm, it looks like you are using the default data dir path of `C:\ProgramData\ryo\lmdb02`. In case anyone else lands here, if you change that in the GUI, then you have to run ryod.exe (or other tools) with `--data-dir D:\path\to\ryo\lmdb02`

You could try downloading the full CLI tools from here: https://github.com/ryo-currency/ryo-currency/releases and try running `ryo-blockchain-import.exe --pop-blocks 1000`

If that doesn't fix it, I am not positive there is a way to un-corrupt the blockchain. lmdb is pretty good at not being corruptible, but unexpected power loss usually does it.

Regarding issue #14, This is one of the things I still need to detect on startup, and prompt the user about it (or attempt at salvage, or popping blocks).

**Comment by mattmill30** [comment]
@mosu-forge Attached is the log from ryo-blockchain-import.exe

Can you provide any further details about the likely nature of the corruption, and whether any tools exist to identify and potentially repair the fault?

[ryo-blockchain-import_pop-blocks-1000.log](https://github.com/ryo-currency/ryo-wallet/files/3066345/ryo-blockchain-import_pop-blocks-1000_11-04-2019.txt)

**Comment by mosu-forge** [comment]
@mattmill30 apologize about the delay. It does look like it was un-recoverable. 

What you can do is every once in a while make a backup of the file, but that will use up an extra ~15GB or so. You could also skip the next step and download the raw blockchain export we provide.

`ryo-blockchain-export.exe` <- this will back up the blockchain to C:\ProgramData\ryo\export\blockchain.raw`
