### ISSUE TITLE
Wallet icon and address not retrieved from blockchain upon recovery from seed

### ISSUE THREAD

**Issue by LeadManPL** [ryo-currency/ryo-wallet#31]
* OS : Ubuntu 18.04.2 LTS
* Version : 1.3.1-0.4.0.1

After recoverying wallet from seed, on main screen wallet icon and address are invisible.
See attached screenshots:

* Original wallet
![blured_Ryo Wallet Atom_004](https://user-images.githubusercontent.com/13769051/58725032-6ad78b80-83de-11e9-8a56-cadcd51b3b16.jpg)

* Recreated from seed walet:
![Zrzut ekranu z 2019-05-31 19-38-17](https://user-images.githubusercontent.com/13769051/58725234-ed604b00-83de-11e9-8c79-984bad36984c.png)

Side note: Icon and address **are** visible inside of the wallet, but again invisible when exiting wallet.

**Comment by mosu-forge** [comment]
Hi @LeadManPL 

Interesting bug. Does creating a new wallet show up in the list? Can you check to see if your restored wallet files are at: C:\ProgramData\ryo\wallets ? Could possibly be a permission issue.

**Comment by LeadManPL** [comment]
@mosu-forge : As in header of my issue: OS : Ubuntu 18.04.2 LTS

**Comment by mosu-forge** [comment]
@LeadManPL what happens if you log in to the wallet, and then log back out of it? The missing icon is because the `walletRYO.address.txt` file is zero bytes as per your `ls -la`

**Comment by LeadManPL** [comment]
That is what I thought (zero length file) but pay attention, that other files differ too.

**Comment by mosu-forge** [comment]
The other files having a different length isn't that strange. The `walletRYO` one in particular is the cache file and when you restore from seed you lose some info, thus it is a bit smaller. 

Do let me know what happens when you log into the wallet without the icon. If that doesn't fix it, delete the .address.txt file and then log into the wallet again. Atom should regenerate address.txt file if it is missing.

Happy Friday 🍻

**Comment by LeadManPL** [comment]
* logging in and back several times didn't fix the icon
* This fixed icon:
  1. Close Atom (BTW, I think you should start using some other name for this wallet: https://atom.io/ )
  1. delete **address.txt**
  1. open Atom - icon still not fixed
  1. login to broken wallet - now file was regenerated and icon and address appeared.
 
I suggest to implement this into wallet retrieve function.
There is a workaround provided.... so closing. Thank you for the help :)
