### ISSUE TITLE
16-64 chars id converstion

### ISSUE THREAD

**Issue by Ryo-RU** [ryo-currency/ryo-wallet#8]
- create tx in Atom to my integrated adress, in [tools](https://ryo-currency.com/address-tools/#make-integrated-address) it asked for 16 chars, so i ended with 123456789123456 (for test purposes) as id which worked fine, and when checkboxing (on sending) "save to adress book" in adress book is showes now:
Payment id: 1234567890123456000000000000000000000000000000000000000000000000

can we check if the rest 48 chars are zeroes, to cut it off?

**Comment by mosu-forge** [comment]
This is fixed in the upcoming Atom 1.1.0 release. Thank you for the enhancement request.
